### Week 1 Lab Python List and Numpy for AI and ML
### Name: Amrita Pudasaini

### To-Do-Task (Exercise on Functions)

In [ ]:
# Task 1
def convert_units(choice, value):
    if choice == 1:
        return value * 3.28084, "Meters to Feet", "ft"
    elif choice == 2:
        return value / 3.28084, "Feet to Meters", "m"
    elif choice == 3:
        return value * 2.20462, "Kilograms to Pounds", "lbs"
    elif choice == 4:
        return value / 2.20462, "Pounds to Kilograms", "kg"
    elif choice == 5:
        return value * 0.264172, "Liters to Gallons", "gal"
    elif choice == 6:
        return value / 0.264172, "Gallons to Liters", "L"
    else:
        return None, None, None
print("Unit Converter")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")
try:
    choice = int(input("Enter your choice (1-6): "))
    value = float(input("Enter the value to convert: "))

    result, conversion_name, unit = convert_units(choice, value)

    if result is not None:
        print(conversion_name + " = " + str(round(result, 2)) + " " + unit)
    else:
        print("Invalid conversion choice.")
except ValueError:
    print("Error: Please enter numeric values only.")

Unit Converter
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Feet to Meters = 1.52 m


In [6]:
#Task 2
def find_sum(numbers):
    return sum(numbers)
def find_average(numbers):
    return sum(numbers) / len(numbers)
def find_maximum(numbers):
    return max(numbers)
def find_minimum(numbers):
    return min(numbers)

print("Mathematical Operations Program")
print("1. Find Sum")
print("2. Find Average")
print("3. Find Maximum")
print("4. Find Minimum")
try:
    choice = int(input("Enter your choice (1-4): "))
    user_input = input("Enter numbers separated by spaces: ")
    numbers = [float(num) for num in user_input.split()]

    if len(numbers) == 0:
        print("Error: List is empty.")
    else:
        if choice == 1:
            print("Sum =", find_sum(numbers))

        elif choice == 2:
            print("Average =", find_average(numbers))

        elif choice == 3:
            print("Maximum =", find_maximum(numbers))

        elif choice == 4:
            print("Minimum =", find_minimum(numbers))

        else:
            print("Invalid choice.")
except ValueError:
    print("Error: Please enter valid numeric values.")

Mathematical Operations Program
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Maximum = 7.0


### 3.2: Exercise on List Manipulation

In [7]:
# Extract every other element
def extract_every_other(lst):
    return lst[::2]

# Return sublist from indexes
def get_sublist(lst, start, end):
    return lst[start:end+1]

# Reverse list using slicing
def reverse_list(lst):
    return lst[::-1]

# Remove first and last
def remove_first_last(lst):
    return lst[1:-1]

# Get first n elements
def get_first_n(lst, n):
    return lst[:n]

# Get last n elements
def get_last_n(lst, n):
    return lst[-n:]

# Reverse skipping one element
def reverse_skip(lst):
    return lst[-2::-2]

# Example list
numbers = [1, 2, 3, 4, 5, 6]
print("Original List:", numbers)
print("Every Other Element:", extract_every_other(numbers))
print("Sublist (2 to 4):", get_sublist(numbers, 2, 4))
print("Reversed List:", reverse_list(numbers))
print("Without First and Last:", remove_first_last(numbers))
print("First 3 Elements:", get_first_n(numbers, 3))
print("Last 2 Elements:", get_last_n(numbers, 2))
print("Reverse Skip List:", reverse_skip(numbers))

Original List: [1, 2, 3, 4, 5, 6]
Every Other Element: [1, 3, 5]
Sublist (2 to 4): [3, 4, 5]
Reversed List: [6, 5, 4, 3, 2, 1]
Without First and Last: [2, 3, 4, 5]
First 3 Elements: [1, 2, 3]
Last 2 Elements: [5, 6]
Reverse Skip List: [5, 3, 1]


### 3.3 Exercise on Nested List

#### Flatten a Nested List

In [ ]:
def flatten(lst):
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)

    return result


nested_list = [[1, 2], [3, 4], [5]]

print("Flattened List:", flatten(nested_list))

Flattened List: [1, 2, 3, 4, 5]


#### Accessing Nested List Elements

In [10]:
def access_nested_element(lst, indices):
    element = lst

    for index in indices:
        element = element[index]

    return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Element:", access_nested_element(lst, [1, 2]))

Element: 6


#### Sum of All Elements in a Nested List

In [11]:
def sum_nested(lst):
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item

    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
print("Sum:", sum_nested(nested_list))

Sum: 21


#### Remove Specific Element from Nested List

In [12]:
def remove_element(lst, elem):
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)

    return result

lst = [[1, 2], [3, 2], [4, 5]]
print("Updated List:", remove_element(lst, 2))

Updated List: [[1], [3], [4, 5]]


#### Find Maximum Element in Nested List

In [13]:
def flatten(lst):
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)

    return result

def find_max(lst):
    return max(flatten(lst))

nested_list = [[1, 2], [3, [4, 5]], 6]
print("Maximum Element:", find_max(nested_list))

Maximum Element: 6


#### Count Occurrences in Nested List

In [14]:
def count_occurrences(lst, elem):
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

lst = [[1, 2], [2, 3], [2, 4]]
print("Occurrences of 2:", count_occurrences(lst, 2))

Occurrences of 2: 3


#### Flatten List of Lists of Lists

In [15]:
def deep_flatten(lst):
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print("Deep Flattened List:", deep_flatten(lst))

Deep Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]


#### Nested List Average

In [16]:
# Flatten nested list
def flatten(lst):
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)

    return result


# Calculate average
def average_nested(lst):
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list)

nested_list = [[1, 2], [3, 4], [5, 6]]
print("Average:", average_nested(nested_list))

Average: 3.5


## Amrita Pudasaini

## To-Do-NumPy

### 9.1 Basic Vector and Matrix Operation with Numpy
#### Problem - 1: Array Creation

#### Initialize Empty Array

In [19]:
import numpy as np
arr = np.empty((2, 2))
print(arr)

[[2.16851034e+243 4.27242994e+180]
 [9.29614703e+199 9.08669024e+223]]


#### Initialize All One Array

In [20]:
import numpy as np
arr = np.ones((4, 2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#### Array Filled With Value

In [21]:
import numpy as np
arr = np.full((3, 3), 7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


#### Zeros Array Like Existing Array

In [22]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
zero_arr = np.zeros_like(arr)
print(zero_arr)

[[0 0]
 [0 0]]


#### Ones Array Like Existing Array

In [23]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
one_arr = np.ones_like(arr)
print(one_arr)

[[1 1]
 [1 1]]


#### Convert List to NumPy Array

In [24]:
import numpy as np
new_list = [1, 2, 3, 4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


## Problem-2 : Array Manipulation

#### Array from 10 to 49

In [25]:
import numpy as np
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Create  3*3 Matrix

In [26]:
import numpy as np
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Identity Matrix

In [27]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Random Array and Mean

In [28]:
import numpy as np
arr = np.random.random(30)
print(arr)
print("Mean =", arr.mean())

[0.75788714 0.74975137 0.21048187 0.91885999 0.62905029 0.15105533
 0.095676   0.85083849 0.52853311 0.93187708 0.03101148 0.12830832
 0.84037622 0.48704687 0.58959427 0.27730845 0.10143039 0.00805544
 0.09745677 0.64202875 0.95128335 0.61992464 0.29526294 0.78192736
 0.922218   0.201126   0.87470712 0.50773417 0.84672114 0.85300329]
Mean = 0.5293511877741376


#### Random 10*10 Array

In [29]:
import numpy as np
arr = np.random.random((10, 10))
print(arr)
print("Minimum =", arr.min())
print("Maximum =", arr.max())

[[0.48134208 0.60793392 0.35001439 0.45017334 0.52577843 0.20565053
  0.76396669 0.15776068 0.85194044 0.12580979]
 [0.92936558 0.78594172 0.39481059 0.43587143 0.57515454 0.86738639
  0.37934055 0.59493747 0.14742295 0.9537114 ]
 [0.76149628 0.90342479 0.93391494 0.89072726 0.83581422 0.1295526
  0.67648176 0.26664158 0.66892237 0.72899318]
 [0.26656626 0.90975713 0.94845507 0.08036331 0.86338512 0.34159046
  0.92492911 0.51774277 0.15782758 0.51137154]
 [0.42730706 0.70720888 0.00885599 0.44821226 0.21747409 0.75479123
  0.43857512 0.47903516 0.06240557 0.37062716]
 [0.45914746 0.22250348 0.13758811 0.14901794 0.4472328  0.48582703
  0.60064236 0.02525911 0.12587704 0.38369907]
 [0.1617036  0.04223374 0.68601756 0.02598947 0.72743867 0.11474437
  0.33675366 0.43287382 0.69601004 0.66953814]
 [0.19251469 0.10473824 0.72077338 0.44616806 0.41840807 0.6420371
  0.70214276 0.78795356 0.99978045 0.13926612]
 [0.63623114 0.75323517 0.41277212 0.03824145 0.20018788 0.72002725
  0.73455894 0

#### Replace Fifth Element

In [30]:
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Reverse Array

In [31]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
reverse_arr = arr[::-1]
print(reverse_arr)

[0 4 0 0 2 1]


#### Border With Ones

In [32]:
import numpy as np
arr = np.zeros((5, 5))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Checkerboard Pattern

In [33]:
import numpy as np
arr = np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem-3: Array Operations

In [34]:
import numpy as np

# Define arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Add arrays
print("Addition:")
print(x + y)

# Subtract arrays
print("\nSubtraction:")
print(x - y)

# Multiply by integer
print("\nMultiplication:")
print(x * 2)

# Square each element
print("\nSquare:")
print(x ** 2)

# Dot products
print("\nDot Product v and w:")
print(np.dot(v, w))

print("\nDot Product x and v:")
print(np.dot(x, v))

print("\nDot Product x and y:")
print(np.dot(x, y))

# Concatenate along rows
print("\nConcatenate x and y:")
print(np.concatenate((x, y), axis=0))

# Concatenate vectors
print("\nConcatenate v and w:")
print(np.concatenate((v, w), axis=0))

Addition:
[[ 6  8]
 [10 13]]

Subtraction:
[[-4 -4]
 [-4 -3]]

Multiplication:
[[ 2  4]
 [ 6 10]]

Square:
[[ 1  4]
 [ 9 25]]

Dot Product v and w:
219

Dot Product x and v:
[29 77]

Dot Product x and y:
[[19 22]
 [50 58]]

Concatenate x and y:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w:
[ 9 10 11 12]


#### Concatenate x and v

####  Explanation of the error: 
Error occurs because x is 2-dimensional while v is 1-dimensional. Both arrays must have same dimensions.

In [36]:
import numpy as np
x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

print(np.concatenate((x, v)))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## Problem- 4: Matrix Operations

#### 1. Prove A × A⁻¹ = I

In [37]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print(result)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


#### 2. Prove AB ≠ BA

In [38]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Multiply AB
AB = np.dot(A, B)

# Multiply BA
BA = np.dot(B, A)

print("AB =")
print(AB)

print("\nBA =")
print(BA)

AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]


#### 3. Prove (AB)ᵀ = BᵀAᵀ

In [39]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

left = np.dot(A, B).T
right = np.dot(B.T, A.T)

print("Left Side:")
print(left)

print("\nRight Side:")
print(right)

Left Side:
[[23 51]
 [13 29]]

Right Side:
[[23 51]
 [13 29]]


#### Solve Linear Equation Using Inverse Method

In [40]:
import numpy as np

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

# Find inverse of A
A_inv = np.linalg.inv(A)

# Solve equation
X = np.dot(A_inv, B)

print("Solution:")
print(X)

Solution:
[ 2.  1. -2.]


#### Solve Using np.linalg.inv()

In [41]:
import numpy as np
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])
B = np.array([-1, -3, 9])

# Using linalg.inv
solution = np.linalg.inv(A).dot(B)

print("x, y, z =", solution)

x, y, z = [ 2.  1. -2.]


## 9.2 Experiment: How Fast is Numpy?

### 1. Element-wise Addition

#### Python

In [42]:
import time
n = 1_000_000
a = list(range(n))
b = list(range(n))

start = time.time()

result = []
for i in range(n):
    result.append(a[i] + b[i])

end = time.time()
print("List Addition Time:", end - start)

List Addition Time: 0.4939002990722656


#### NumPy Array

In [43]:
import numpy as np
import time

n = 1_000_000

a = np.arange(n)
b = np.arange(n)

start = time.time()

result = a + b
end = time.time()
print("NumPy Addition Time:", end - start)

NumPy Addition Time: 0.11730194091796875


#### 2. Element-wise Multiplication

#### Python List

In [44]:
import time

n = 1_000_000
a = list(range(n))
b = list(range(n))
start = time.time()
result = []
for i in range(n):
    result.append(a[i] * b[i])

end = time.time()
print("List Multiplication Time:", end - start)

List Multiplication Time: 0.2720677852630615


#### NumPy Array

In [45]:
import numpy as np
import time
n = 1_000_000
a = np.arange(n)
b = np.arange(n)

start = time.time()

result = a * b
end = time.time()
print("NumPy Multiplication Time:", end - start)

NumPy Multiplication Time: 0.04396963119506836


#### 3. Dot Product

#### Python List

In [46]:
import time

n = 1_000_000
a = list(range(n))
b = list(range(n))
start = time.time()

dot = 0
for i in range(n):
    dot += a[i] * b[i]

end = time.time()
print("List Dot Product Time:", end - start)

List Dot Product Time: 0.23284387588500977


#### NumPy Array

In [47]:
import numpy as np
import time

n = 1_000_000
a = np.arange(n)
b = np.arange(n)

start = time.time()
dot = np.dot(a, b)
end = time.time()
print("NumPy Dot Product Time:", end - start)

NumPy Dot Product Time: 0.013791084289550781


#### 4. Matrix Multiplication

#### Python List

In [1]:
import time
size = 1000

A = [[1 for _ in range(size)] for _ in range(size)]
B = [[1 for _ in range(size)] for _ in range(size)]

start = time.time()
result = []
for i in range(size):
    row = []
    for j in range(size):
        s = 0
        for k in range(size):
            s += A[i][k] * B[k][j]
        row.append(s)
    result.append(row)
end = time.time()
print("List Matrix Multiplication Time:", end - start)

List Matrix Multiplication Time: 214.10886526107788


#### NumPy List

In [2]:
import numpy as np
import time

size = 1000

A = np.ones((size, size))
B = np.ones((size, size))

start = time.time()

result = np.dot(A, B)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start)

NumPy Matrix Multiplication Time: 0.03852534294128418
